FROM rockylinux/rockylinux:9.0

ARG LM_LICENSE_FILE
ARG YOSYSHQ_LICENSE
ARG VCS_HOME
ARG TABBY_HOME
ARG VPR_HOME
ARG MILL_HOME
ARG SSV231_HOME

ENV LM_LICENSE_FILE=${LM_LICENSE_FILE}
ENV YOSYSHQ_LICENSE=${YOSYSHQ_LICENSE}
ENV VCS_HOME=${VCS_HOME}
ENV TABBY_HOME=${TABBY_HOME}
ENV VPR_HOME=${VPR_HOME}
ENV VTR_ROOT=${VPR_HOME}
ENV MILL_ROOT=${MILL_HOME}

# The below tool ENV may need to be modified for new systems
# For the system under test, all tools are available under /opt

ENV PATH=$VCS_HOME/linux64/bin:$PATH
ENV PATH=$TABBY_HOME/bin:$PATH
ENV PATH=$VPR_HOME/build/vpr:$PATH
ENV PATH=$MILL_HOME:$PATH

ENV LC_CTYPE=C

RUN dnf install -y \
   'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled \
   crb
RUN dnf install -y \
   epel-release
   
RUN dnf check-update || true
RUN dnf upgrade -y

# TODO: Trim what isn't needed
RUN dnf install -y \
   gdb sudo \
   gcc gcc-c++ \
   glibc-locale-source \
   make cmake \
   autoconf \
   bison flex \
   rpm-build \
   rpmdevtools \
   grub2 \
   bc \
   csh \
   wget \
   kernel-headers kernel-devel \
   ncurses ncurses-libs ncurses-devel ncurses-compat-libs \
   boost boost-devel \
   libxml2 libxml2-devel \
   elfutils-libelf-devel \
   json-c-devel \
   hwloc hwloc-devel \
   tbb-devel \
   cli11-devel \
   spdlog-devel \
   openssl-devel \
   uuid libuuid-devel \
   libedit-devel \
   systemd-devel \
   yaml-cpp-devel \
   libcap-devel \
   fontconfig \
   nmap \
   libpcap libtool numactl-libs libedit libnsl libXdmcp libXext \
   java-11-openjdk.x86_64

RUN localedef -f UTF-8 -i en_US en_US.UTF-8

RUN dnf install -y \
  python3-pip

RUN python3 -m pip install \
  --upgrade pip

# Maybe copy over a requirements.txt if Python is needed
# COPY ofs_extratool.sh $IOFS_BUILD_ROOT
RUN python3 -m pip install \
   jsonschema \
   --no-input

# GOAL: remove all of these
RUN dnf install -y \
   nano \
   vim \
   git \
   rsync \
   doxygen \
   net-tools \
   dwarves

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN dnf check-update || true
RUN dnf upgrade -y

RUN dnf update -y
RUN dnf install ksh -y

RUN dnf install -y yum-utils
RUN dnf config-manager --set-enabled devel
RUN dnf update -y
RUN dnf install redhat-lsb-core -y

RUN dnf install libXScrnSaver -y

RUN dnf install openmotif -y 

RUN dnf install libpng12 -y

RUN dnf install mesa-libGLU -y

WORKDIR /home