FROM metastability_tools:base

ARG UNAME='YOUR USER NAME'
ARG UID='YOUR UID'
ARG GID='YOUR GID'
ARG LM_LICENSE_FILE='License server'

RUN localedef -f UTF-8 -i en_US en_US.UTF-8
SHELL ["/bin/bash", "-c"]
RUN groupadd -g ${GID} -o ${UNAME}
RUN useradd -m -u ${UID} -g ${GID} -o -s /bin/bash ${UNAME}



USER $UNAME
WORKDIR /home/$UNAME

# ENV PATH=...:$PATH

CMD /bin/bash
